/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/castle.glb 
Author: SantyFrow (https://sketchfab.com/santyfrow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-medieval-castle-room-e3d1e0562a9740ed8b759558bcaf0a36
Title: Stylized Medieval Castle Room
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";
import { scale } from "framer-motion";
export function Castle(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF("models/castle.glb");
  return (
    <group {...props} dispose={null}>
      <motion.group
        position={[194.259, 507.866, 145.109]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={50}
        animate={{ scale: section === 0 ? 100 : 0 }}
      >
        <mesh
          geometry={nodes.Cylinder011_glass_0.geometry}
          material={materials.glass}
        />
        <mesh
          geometry={nodes.Cylinder011_stuff_0.geometry}
          material={materials.stuff}
        />
      </motion.group>
      <motion.group
        position={[194.259, 499.839, 267.249]}
        rotation={[3.128, -1.203, -0.013]}
        scale={50}
        animate={{ scale: section === 0 ? 100 : 0 }}
      >
        <mesh
          geometry={nodes.Cylinder014_glass_0.geometry}
          material={materials.glass}
        />
        <mesh
          geometry={nodes.Cylinder014_stuff_0.geometry}
          material={materials.stuff}
        />
      </motion.group>
      <motion.group
        position={[194.259, 501.105, 192.524]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={50}
        animate={{ scale: section === 0 ? 100 : 0 }}
      >
        <mesh
          geometry={nodes.Cylinder018_glass_0.geometry}
          material={materials.glass}
        />
        <mesh
          geometry={nodes.Cylinder018_stuff_0.geometry}
          material={materials.stuff}
        />
      </motion.group>
      <motion.group
        position={[194.259, 516.839, 388.276]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={50}
        animate={{ scale: section === 0 ? 100 : 0 }}
      >
        <mesh
          geometry={nodes.Cylinder019_glass_0.geometry}
          material={materials.glass}
        />
        <mesh
          geometry={nodes.Cylinder019_stuff_0.geometry}
          material={materials.stuff}
        />
      </motion.group>
      <motion.group
        position={[194.259, 516.839, 447.695]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={50}
        animate={{ scale: section === 0 ? 100 : 0 }}
      >
        <mesh
          geometry={nodes.Cylinder020_glass_0.geometry}
          material={materials.glass}
        />
        <mesh
          geometry={nodes.Cylinder020_stuff_0.geometry}
          material={materials.stuff}
        />
      </motion.group>
      <motion.group
        position={[-383.636, 177.263, 923.051]}
        rotation={[-Math.PI / 2, 0, 2.845]}
        scale={50}
        animate={{ scale: section === 0 ? 100 : 0 }}
      >
        <mesh
          geometry={nodes.Cylinder029_glass_0.geometry}
          material={materials.glass}
        />
        <mesh
          geometry={nodes.Cylinder029_stuff_0.geometry}
          material={materials.stuff}
        />
      </motion.group>
      <motion.group
        position={[-635.749, 177.263, 832.266]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={50}
        animate={{ scale: section === 0 ? 100 : 0 }}
      >
        <mesh
          geometry={nodes.Cylinder030_glass_0.geometry}
          material={materials.glass}
        />
        <mesh
          geometry={nodes.Cylinder030_stuff_0.geometry}
          material={materials.stuff}
        />
      </motion.group>
      <mesh
        geometry={nodes.Cylinder_stuff_0.geometry}
        material={materials.stuff}
        position={[-992.121, 511.888, 56.047]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube018_stuff_0.geometry}
        material={materials.stuff}
        position={[201.123, 478.083, 203.712]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube020_stuff_0.geometry}
        material={materials.stuff}
        position={[201.123, 466.426, 131.438]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube019_stuff_0.geometry}
        material={materials.stuff}
        position={[201.123, 478.083, 418.236]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube021_stuff_0.geometry}
        material={materials.stuff}
        position={[201.123, 466.426, 345.962]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube023_stuff_0.geometry}
        material={materials.stuff}
        position={[-149.767, 375.01, 29.082]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder001_stuff_0.geometry}
        material={materials.stuff}
        position={[233.812, 478.041, 757.288]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder004_stuff_0.geometry}
        material={materials.stuff}
        position={[-149.767, 362.375, 40.888]}
        rotation={[-1.448, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder005_stuff_0.geometry}
        material={materials.stuff}
        position={[-149.767, 400.503, 45.85]}
        rotation={[-1.448, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube025_stuff_0.geometry}
        material={materials.stuff}
        position={[204.944, 375.01, 1250.521]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder008_stuff_0.geometry}
        material={materials.stuff}
        position={[191.416, 362.162, 1250.521]}
        rotation={[-Math.PI / 2, -0.123, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder009_stuff_0.geometry}
        material={materials.stuff}
        position={[188.176, 400.503, 1250.521]}
        rotation={[-Math.PI / 2, -0.123, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Sphere_stuff_0.geometry}
        material={materials.stuff}
        position={[-868.64, 142.929, 165.803]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder010_stuff_0.geometry}
        material={materials.stuff}
        position={[-149.767, 400.503, 45.85]}
        rotation={[-1.448, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder012_stuff_0.geometry}
        material={materials.stuff}
        position={[-149.794, 437.721, 50.198]}
        rotation={[-1.448, 0, 0.085]}
        scale={100}
      />
      <mesh
        geometry={nodes.Sphere001_glass_0.geometry}
        material={materials.glass}
        position={[-868.64, 133.056, 165.803]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder016_stuff_0.geometry}
        material={materials.stuff}
        position={[187.412, 400.503, 1250.337]}
        rotation={[-Math.PI / 2, -0.123, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder017_stuff_0.geometry}
        material={materials.stuff}
        position={[183.064, 437.721, 1250.309]}
        rotation={[-Math.PI / 2, -0.123, -0.684]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube040_stuff_0.geometry}
        material={materials.stuff}
        position={[69.024, 375.01, 29.082]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder006_stuff_0.geometry}
        material={materials.stuff}
        position={[69.024, 362.375, 40.888]}
        rotation={[-1.448, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder007_stuff_0.geometry}
        material={materials.stuff}
        position={[69.024, 400.503, 45.85]}
        rotation={[-1.448, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder015_stuff_0.geometry}
        material={materials.stuff}
        position={[68.997, 437.721, 50.198]}
        rotation={[-1.448, 0, 0.085]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder025_stuff_0.geometry}
        material={materials.stuff}
        position={[-695.26, 174.719, 832.267]}
        rotation={[-Math.PI / 2, 0, 3.076]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder026_stuff_0.geometry}
        material={materials.stuff}
        position={[-428.764, 174.719, 845.994]}
        rotation={[-Math.PI / 2, 0, 3.076]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder027_stuff_0.geometry}
        material={materials.stuff}
        position={[41.52, 123.923, 1303.809]}
        rotation={[-Math.PI / 2, 0, 3.076]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder028_stuff_0.geometry}
        material={materials.stuff}
        position={[150.4, 159.062, 1023.289]}
        rotation={[-Math.PI / 2, 0, 3.076]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder065_stuff_0.geometry}
        material={materials.stuff}
        position={[-643.197, 161.653, 880.103]}
        rotation={[-0.347, -1.036, -0.044]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder066_stuff_0.geometry}
        material={materials.stuff}
        position={[-565.198, 150.296, 886.217]}
        rotation={[-Math.PI / 2, 0, 1.389]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder067_stuff_0.geometry}
        material={materials.stuff}
        position={[-555.855, 150.477, 873.188]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder068_stuff_0.geometry}
        material={materials.stuff}
        position={[-556.679, 152.672, 887.996]}
        rotation={[0.14, -0.226, -1.539]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder069_stuff_0.geometry}
        material={materials.stuff}
        position={[-443.869, 148.581, 788.324]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder184_stuff_0.geometry}
        material={materials.stuff}
        position={[175.141, 132.68, 832.822]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder002_stuff_0.geometry}
        material={materials.stuff}
        position={[69.024, 400.503, 45.85]}
        rotation={[-1.448, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Plane002_glass_0.geometry}
        material={materials.glass}
        position={[-707.389, 149.154, 926.028]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Plane003_glass_0.geometry}
        material={materials.glass}
        position={[175.141, 181.544, 832.822]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder098_coin_0.geometry}
        material={materials.coin}
        position={[38.039, -7.391, 457.965]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder099_coin_0.geometry}
        material={materials.coin}
        position={[36.599, -3.336, 456.871]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder100_coin_0.geometry}
        material={materials.coin}
        position={[39.057, 0.656, 455.906]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder101_coin_0.geometry}
        material={materials.coin}
        position={[36.504, 4.609, 455.247]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder102_coin_0.geometry}
        material={materials.coin}
        position={[39.212, 8.585, 455.973]}
        rotation={[-Math.PI / 2, 0, -2.851]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder103_coin_0.geometry}
        material={materials.coin}
        position={[38.118, 12.641, 457.413]}
        rotation={[-Math.PI / 2, 0, -2.851]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder104_coin_0.geometry}
        material={materials.coin}
        position={[37.153, 16.632, 454.956]}
        rotation={[-Math.PI / 2, 0, -2.851]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder105_coin_0.geometry}
        material={materials.coin}
        position={[36.494, 20.586, 457.508]}
        rotation={[-Math.PI / 2, 0, -2.851]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder106_coin_0.geometry}
        material={materials.coin}
        position={[39.132, 24.561, 456.088]}
        rotation={[-Math.PI / 2, 0, -0.463]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder107_coin_0.geometry}
        material={materials.coin}
        position={[38.038, 28.616, 457.528]}
        rotation={[-Math.PI / 2, 0, -0.463]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder108_coin_0.geometry}
        material={materials.coin}
        position={[37.073, 32.608, 455.07]}
        rotation={[-Math.PI / 2, 0, -0.463]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder109_coin_0.geometry}
        material={materials.coin}
        position={[36.414, 36.561, 457.623]}
        rotation={[-Math.PI / 2, 0, -0.463]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder110_coin_0.geometry}
        material={materials.coin}
        position={[37.14, 40.537, 454.915]}
        rotation={[-Math.PI / 2, 0, -1.28]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder111_coin_0.geometry}
        material={materials.coin}
        position={[38.58, 44.593, 456.009]}
        rotation={[-Math.PI / 2, 0, -1.28]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder112_coin_0.geometry}
        material={materials.coin}
        position={[36.123, 48.584, 456.974]}
        rotation={[-Math.PI / 2, 0, -1.28]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder113_coin_0.geometry}
        material={materials.coin}
        position={[38.675, 52.538, 457.633]}
        rotation={[-Math.PI / 2, 0, -1.28]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder114_coin_0.geometry}
        material={materials.coin}
        position={[46.58, -7.391, 495.206]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder115_coin_0.geometry}
        material={materials.coin}
        position={[45.14, -3.336, 494.112]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder116_coin_0.geometry}
        material={materials.coin}
        position={[47.597, 0.656, 493.147]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder117_coin_0.geometry}
        material={materials.coin}
        position={[45.045, 4.609, 492.489]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder118_coin_0.geometry}
        material={materials.coin}
        position={[47.753, 8.585, 493.214]}
        rotation={[-Math.PI / 2, 0, -2.851]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder119_coin_0.geometry}
        material={materials.coin}
        position={[46.658, 12.641, 494.655]}
        rotation={[-Math.PI / 2, 0, -2.851]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder120_coin_0.geometry}
        material={materials.coin}
        position={[45.693, 16.632, 492.197]}
        rotation={[-Math.PI / 2, 0, -2.851]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder121_coin_0.geometry}
        material={materials.coin}
        position={[45.035, 20.586, 494.75]}
        rotation={[-Math.PI / 2, 0, -2.851]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder122_coin_0.geometry}
        material={materials.coin}
        position={[47.673, 24.561, 493.329]}
        rotation={[-Math.PI / 2, 0, -0.463]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder123_coin_0.geometry}
        material={materials.coin}
        position={[46.578, 28.616, 494.769]}
        rotation={[-Math.PI / 2, 0, -0.463]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder124_coin_0.geometry}
        material={materials.coin}
        position={[27.68, -7.391, 416.985]}
        rotation={[-Math.PI / 2, 0, -0.316]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder125_coin_0.geometry}
        material={materials.coin}
        position={[26.808, -3.336, 418.57]}
        rotation={[-Math.PI / 2, 0, -0.316]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder126_coin_0.geometry}
        material={materials.coin}
        position={[25.494, 0.656, 416.28]}
        rotation={[-Math.PI / 2, 0, -0.316]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder127_coin_0.geometry}
        material={materials.coin}
        position={[25.216, 4.609, 418.902]}
        rotation={[-Math.PI / 2, 0, -0.316]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder128_coin_0.geometry}
        material={materials.coin}
        position={[25.538, 8.585, 416.117]}
        rotation={[-Math.PI / 2, 0, -1.133]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder129_coin_0.geometry}
        material={materials.coin}
        position={[27.122, 12.641, 416.989]}
        rotation={[-Math.PI / 2, 0, -1.133]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder130_coin_0.geometry}
        material={materials.coin}
        position={[24.833, 16.632, 418.303]}
        rotation={[-Math.PI / 2, 0, -1.133]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder131_coin_0.geometry}
        material={materials.coin}
        position={[27.454, 20.586, 418.581]}
        rotation={[-Math.PI / 2, 0, -1.133]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder132_coin_0.geometry}
        material={materials.coin}
        position={[25.663, 24.561, 416.179]}
        rotation={[-Math.PI / 2, 0, 1.255]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder133_coin_0.geometry}
        material={materials.coin}
        position={[27.247, 28.616, 417.051]}
        rotation={[-Math.PI / 2, 0, 1.255]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder134_coin_0.geometry}
        material={materials.coin}
        position={[25.663, 32.597, 416.179]}
        rotation={[-Math.PI / 2, 0, 1.255]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder135_coin_0.geometry}
        material={materials.coin}
        position={[27.247, 36.653, 417.051]}
        rotation={[-Math.PI / 2, 0, 1.255]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder136_coin_0.geometry}
        material={materials.coin}
        position={[36.034, 56.54, 456.632]}
        rotation={[-Math.PI / 2, 0, 1.108]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder137_coin_0.geometry}
        material={materials.coin}
        position={[38.587, 60.493, 457.291]}
        rotation={[-Math.PI / 2, 0, 1.108]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder138_coin_0.geometry}
        material={materials.coin}
        position={[35.878, 64.47, 456.565]}
        rotation={[-Math.PI / 2, 0, 0.29]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder139_coin_0.geometry}
        material={materials.coin}
        position={[36.973, 68.525, 455.125]}
        rotation={[-Math.PI / 2, 0, 0.29]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder140_coin_0.geometry}
        material={materials.coin}
        position={[37.938, 72.517, 457.582]}
        rotation={[-Math.PI / 2, 0, 0.29]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder141_coin_0.geometry}
        material={materials.coin}
        position={[38.596, 76.47, 455.029]}
        rotation={[-Math.PI / 2, 0, 0.29]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder146_coin_0.geometry}
        material={materials.coin}
        position={[-182.284, -6.973, 343.915]}
        rotation={[-1.571, 0, 0.681]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder152_coin_0.geometry}
        material={materials.coin}
        position={[-224.636, -6.976, 333.235]}
        rotation={[-1.571, 0, -0.379]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder155_coin_0.geometry}
        material={materials.coin}
        position={[-56.184, -6.977, 408.423]}
        rotation={[-1.571, -0.001, 0.528]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder157_coin_0.geometry}
        material={materials.coin}
        position={[-106.048, -6.974, 396.343]}
        rotation={[-1.571, 0, 0.929]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder158_coin_0.geometry}
        material={materials.coin}
        position={[-90.66, -4.081, 384.096]}
        rotation={[-1.855, 0.145, 0.292]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder159_coin_0.geometry}
        material={materials.coin}
        position={[-128.406, -6.973, 366.604]}
        rotation={[-1.571, 0, 1.215]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder160_coin_0.geometry}
        material={materials.coin}
        position={[-125.405, -6.975, 339.676]}
        rotation={[-1.571, 0, 1.258]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder161_coin_0.geometry}
        material={materials.coin}
        position={[-168.046, -6.974, 311.842]}
        rotation={[-1.571, 0, 2.087]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder163_coin_0.geometry}
        material={materials.coin}
        position={[-38.485, -6.974, 456.733]}
        rotation={[-1.571, 0, 0.882]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder165_coin_0.geometry}
        material={materials.coin}
        position={[-57.957, -6.973, 439.422]}
        rotation={[-1.571, 0, -0.117]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder167_coin_0.geometry}
        material={materials.coin}
        position={[-103.751, -6.973, 422.143]}
        rotation={[-1.571, 0, 0.4]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder168_coin_0.geometry}
        material={materials.coin}
        position={[-82.126, -6.974, 406.277]}
        rotation={[-1.571, 0, 2.335]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder169_coin_0.geometry}
        material={materials.coin}
        position={[-131.916, -6.974, 395.013]}
        rotation={[-1.571, 0, 0.908]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder170_coin_0.geometry}
        material={materials.coin}
        position={[-113.003, -3.274, 371.558]}
        rotation={[-1.627, 0.403, -2.086]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder171_coin_0.geometry}
        material={materials.coin}
        position={[-163.859, -6.973, 378.929]}
        rotation={[-1.571, 0, 0.485]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder173_coin_0.geometry}
        material={materials.coin}
        position={[-75.421, -6.976, 472.102]}
        rotation={[-1.571, -0.001, 0.325]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder174_coin_0.geometry}
        material={materials.coin}
        position={[-11.037, -6.099, 457.979]}
        rotation={[1.479, 0.051, -1.613]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder175_coin_0.geometry}
        material={materials.coin}
        position={[-102.506, -6.973, 450.323]}
        rotation={[-1.571, 0, 0.608]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder176_coin_0.geometry}
        material={materials.coin}
        position={[-81.848, -4.936, 447.663]}
        rotation={[-1.693, 0.188, 1.498]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder177_coin_0.geometry}
        material={materials.coin}
        position={[-137.865, -6.973, 431.464]}
        rotation={[-1.571, 0, 1.207]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder178_coin_0.geometry}
        material={materials.coin}
        position={[-142.073, -2.268, 416.972]}
        rotation={[-2.091, 0.026, -0.054]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder179_coin_0.geometry}
        material={materials.coin}
        position={[-162.381, -6.974, 404.938]}
        rotation={[-1.571, 0, 0.631]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder180_coin_0.geometry}
        material={materials.coin}
        position={[-153.884, -0.573, 400.685]}
        rotation={[-2.073, 0.543, -0.364]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder181_coin_0.geometry}
        material={materials.coin}
        position={[-204.634, -6.977, 390.422]}
        rotation={[-1.571, 0.001, 1.155]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder182_coin_0.geometry}
        material={materials.coin}
        position={[-187.877, -6.973, 369.214]}
        rotation={[-1.571, 0, -0.699]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder183_coin_0.geometry}
        material={materials.coin}
        position={[-193.769, -6.973, 314.887]}
        rotation={[-1.571, 0, -1.09]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder185_coin_0.geometry}
        material={materials.coin}
        position={[-142.798, 0.58, 360.734]}
        rotation={[-1.935, -0.454, 2.884]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder187_coin_0.geometry}
        material={materials.coin}
        position={[-123.804, 0.359, 424.968]}
        rotation={[-1.377, 0.381, -2.108]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder188_coin_0.geometry}
        material={materials.coin}
        position={[-97.287, -0.566, 417.056]}
        rotation={[-1.63, 0.078, 2.138]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder190_coin_0.geometry}
        material={materials.coin}
        position={[-37.978, -4.852, 409.445]}
        rotation={[-1.562, 0.233, -2.506]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder191_coin_0.geometry}
        material={materials.coin}
        position={[-8.52, -6.973, 424.465]}
        rotation={[-1.571, 0, 2.682]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder193_coin_0.geometry}
        material={materials.coin}
        position={[-34.277, -3.123, 362.342]}
        rotation={[-1.93, -0.097, 2.732]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder196_coin_0.geometry}
        material={materials.coin}
        position={[112.462, -6.002, 415.099]}
        rotation={[1.573, 0.115, 0.223]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder197_coin_0.geometry}
        material={materials.coin}
        position={[-72.871, -3.19, 428.849]}
        rotation={[-1.981, -0.074, -2.258]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder198_coin_0.geometry}
        material={materials.coin}
        position={[-22.201, -3.135, 434.675]}
        rotation={[-1.334, -0.058, -0.395]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder199_coin_0.geometry}
        material={materials.coin}
        position={[-147.909, -2.258, 440.579]}
        rotation={[-1.268, -0.099, 0.542]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder200_coin_0.geometry}
        material={materials.coin}
        position={[-45.365, -2.95, 432.758]}
        rotation={[1.313, -0.365, 1.066]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder201_coin_0.geometry}
        material={materials.coin}
        position={[-163.193, -6.973, 485.19]}
        rotation={[-Math.PI / 2, 0, -1.986]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder202_coin_0.geometry}
        material={materials.coin}
        position={[-179.539, -6.384, 511.311]}
        rotation={[1.498, -0.013, 2.832]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder082_coin_0.geometry}
        material={materials.coin}
        position={[-234.385, -6.973, 386.134]}
        rotation={[-Math.PI / 2, 0, 1.163]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder083_coin_0.geometry}
        material={materials.coin}
        position={[-213.933, -6.974, 363.676]}
        rotation={[-1.571, 0, -1.109]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder088_coin_0.geometry}
        material={materials.coin}
        position={[-120.742, -2.535, 405.208]}
        rotation={[-1.211, 0.034, -1.286]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder089_coin_0.geometry}
        material={materials.coin}
        position={[-105.461, 2.361, 364.418]}
        rotation={[-1.7, -0.028, -0.48]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder090_coin_0.geometry}
        material={materials.coin}
        position={[-141.459, -1.66, 387.755]}
        rotation={[-2.107, -0.262, 0.658]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder092_coin_0.geometry}
        material={materials.coin}
        position={[-151.426, -1.761, 374.135]}
        rotation={[-2.092, 0.266, 1.907]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder093_coin_0.geometry}
        material={materials.coin}
        position={[-161.58, -3.108, 356.752]}
        rotation={[-1.882, -0.294, 2.664]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder094_coin_0.geometry}
        material={materials.coin}
        position={[-63.237, -6.973, 494.962]}
        rotation={[-1.571, 0, 1.161]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder095_coin_0.geometry}
        material={materials.coin}
        position={[-26.704, -6.305, 487.334]}
        rotation={[-1.633, -0.055, -3.058]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder096_coin_0.geometry}
        material={materials.coin}
        position={[-100.478, -6.975, 479.58]}
        rotation={[-1.571, 0, 0.372]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder097_coin_0.geometry}
        material={materials.coin}
        position={[-88.558, -0.687, 469.137]}
        rotation={[-2.117, -0.17, -0.852]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder142_coin_0.geometry}
        material={materials.coin}
        position={[-129.414, -6.976, 455.948]}
        rotation={[-1.571, 0, 0.609]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder143_coin_0.geometry}
        material={materials.coin}
        position={[-114.971, -1.858, 443.684]}
        rotation={[-2.114, -0.175, -0.405]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder144_coin_0.geometry}
        material={materials.coin}
        position={[-165.454, -6.974, 430.657]}
        rotation={[-1.571, 0, 0.052]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder145_coin_0.geometry}
        material={materials.coin}
        position={[-171.253, 1.297, 401.368]}
        rotation={[-1.862, -0.948, 0.101]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder147_coin_0.geometry}
        material={materials.coin}
        position={[-188.825, -6.974, 414.275]}
        rotation={[-1.571, 0, 0.266]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder148_coin_0.geometry}
        material={materials.coin}
        position={[-206.706, 3.854, 369.621]}
        rotation={[-1.622, 0.417, -1.533]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder149_coin_0.geometry}
        material={materials.coin}
        position={[-113.975, -6.973, 520.743]}
        rotation={[-Math.PI / 2, 0, 2.101]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder150_coin_0.geometry}
        material={materials.coin}
        position={[-86.394, -6.973, 506.567]}
        rotation={[-Math.PI / 2, 0, -0.461]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder151_coin_0.geometry}
        material={materials.coin}
        position={[-124.593, -6.973, 496.797]}
        rotation={[-1.571, 0, 0.689]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder203_coin_0.geometry}
        material={materials.coin}
        position={[-139.805, -3.54, 492.738]}
        rotation={[-1.638, -0.372, 0.511]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder204_coin_0.geometry}
        material={materials.coin}
        position={[-197.569, -6.973, 486.615]}
        rotation={[-Math.PI / 2, 0, 1.907]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder205_coin_0.geometry}
        material={materials.coin}
        position={[-164.305, -6.973, 459.32]}
        rotation={[-1.571, 0, 0.498]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder206_coin_0.geometry}
        material={materials.coin}
        position={[-190.928, -6.973, 454.126]}
        rotation={[-1.571, 0, 1.49]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder207_coin_0.geometry}
        material={materials.coin}
        position={[-216.794, -6.817, 454.49]}
        rotation={[-1.573, -0.026, -2.748]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder208_coin_0.geometry}
        material={materials.coin}
        position={[-236.354, -6.973, 437.365]}
        rotation={[-Math.PI / 2, 0, 1.221]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder209_coin_0.geometry}
        material={materials.coin}
        position={[-230.344, -6.795, 412.049]}
        rotation={[1.585, 0.025, -2.456]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder210_coin_0.geometry}
        material={materials.coin}
        position={[-206.6, -3.929, 337.744]}
        rotation={[-1.729, 0.296, 2.3]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder212_coin_0.geometry}
        material={materials.coin}
        position={[-210.299, -6.973, 428.758]}
        rotation={[-1.571, 0, -1.025]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder213_coin_0.geometry}
        material={materials.coin}
        position={[-181.178, -1.434, 392.204]}
        rotation={[1.248, 0.536, -1.316]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder214_coin_0.geometry}
        material={materials.coin}
        position={[-185.718, -1.738, 427.999]}
        rotation={[-1.199, 0.03, -1.991]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder215_coin_0.geometry}
        material={materials.coin}
        position={[-180.375, -1.619, 444.646]}
        rotation={[-1.417, 0.171, 2.532]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder216_coin_0.geometry}
        material={materials.coin}
        position={[-106.036, -1.79, 493.298]}
        rotation={[-1.135, 0.134, -1.788]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder217_coin_0.geometry}
        material={materials.coin}
        position={[-95.728, -1.576, 508.1]}
        rotation={[1.709, 0.129, -1.138]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder220_coin_0.geometry}
        material={materials.coin}
        position={[-145.331, -4.044, 468.406]}
        rotation={[-1.381, -0.004, -2.86]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder221_coin_0.geometry}
        material={materials.coin}
        position={[-121.955, -2.762, 470.28]}
        rotation={[1.901, -0.07, -1.125]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder222_coin_0.geometry}
        material={materials.coin}
        position={[-185.849, -6.973, 536.511]}
        rotation={[Math.PI / 2, 0, -1.823]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder223_coin_0.geometry}
        material={materials.coin}
        position={[-200.382, -6.567, 557.815]}
        rotation={[1.534, -0.04, -0.234]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder224_coin_0.geometry}
        material={materials.coin}
        position={[-159.488, -6.973, 532.669]}
        rotation={[-Math.PI / 2, 0, 2.636]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder225_coin_0.geometry}
        material={materials.coin}
        position={[-153.71, -5.489, 564.725]}
        rotation={[-1.615, 0.172, 1.127]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder091_coin_0.geometry}
        material={materials.coin}
        position={[-57.324, -6.974, 357.825]}
        rotation={[-1.571, 0, 0.257]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder162_coin_0.geometry}
        material={materials.coin}
        position={[-55.222, -0.925, 347.391]}
        rotation={[-2.206, 0.259, 0.25]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder172_coin_0.geometry}
        material={materials.coin}
        position={[-99.408, -6.973, 338.139]}
        rotation={[-1.571, 0, 0.907]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder186_coin_0.geometry}
        material={materials.coin}
        position={[-98.681, -1.658, 322.788]}
        rotation={[-2.003, 0.418, 0.114]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder192_coin_0.geometry}
        material={materials.coin}
        position={[-15.913, -6.973, 396.996]}
        rotation={[-1.571, 0, 2.728]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder194_coin_0.geometry}
        material={materials.coin}
        position={[-21.748, -6.973, 371.76]}
        rotation={[1.571, 0, 1.986]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder226_coin_0.geometry}
        material={materials.coin}
        position={[-83.098, -6.974, 360.403]}
        rotation={[-1.571, 0, 2.127]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder227_coin_0.geometry}
        material={materials.coin}
        position={[-94.452, 5.651, 340.625]}
        rotation={[-0.651, -0.495, -2.327]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder228_coin_0.geometry}
        material={materials.coin}
        position={[-113.519, -3.648, 323.381]}
        rotation={[-1.936, 0.011, 0.867]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder229_coin_0.geometry}
        material={materials.coin}
        position={[-142.497, -6.974, 316.101]}
        rotation={[-1.571, 0, -3.087]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder230_coin_0.geometry}
        material={materials.coin}
        position={[-136.815, -2.667, 301.228]}
        rotation={[-2.039, 0.086, 1.24]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder231_coin_0.geometry}
        material={materials.coin}
        position={[-68.191, -3.214, 379.987]}
        rotation={[-1.98, -0.06, -0.337]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder232_coin_0.geometry}
        material={materials.coin}
        position={[-82.247, -2.307, 335.02]}
        rotation={[-1.48, 0.451, -1.55]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder233_coin_0.geometry}
        material={materials.coin}
        position={[-73.854, -2.195, 339.953]}
        rotation={[-1.47, 0.464, -1.165]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder234_coin_0.geometry}
        material={materials.coin}
        position={[-121.396, -3.145, 311.052]}
        rotation={[-1.987, -0.066, -0.381]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder235_coin_0.geometry}
        material={materials.coin}
        position={[-67.131, -4.066, 390.462]}
        rotation={[-1.886, -0.052, 1.294]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder236_coin_0.geometry}
        material={materials.coin}
        position={[-44.765, -6.976, 384.05]}
        rotation={[-1.571, -0.001, 0.591]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder237_coin_0.geometry}
        material={materials.coin}
        position={[-115.044, -2.043, 346.959]}
        rotation={[-1.262, 0.113, 1.013]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder238_coin_0.geometry}
        material={materials.coin}
        position={[-92.732, -1.275, 361.277]}
        rotation={[1.318, 0.553, 1.082]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder239_coin_0.geometry}
        material={materials.coin}
        position={[-148.097, -1.585, 328.152]}
        rotation={[-1.205, 0.025, 0.775]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder240_coin_0.geometry}
        material={materials.coin}
        position={[-198.999, -5.294, 286.082]}
        rotation={[1.43, -0.128, -3.065]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder242_coin_0.geometry}
        material={materials.coin}
        position={[-137.182, -1.807, 359.762]}
        rotation={[-1.935, -0.454, -0.862]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder243_coin_0.geometry}
        material={materials.coin}
        position={[-145.355, -1.156, 338.353]}
        rotation={[2.004, -0.04, -2.643]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder247_coin_0.geometry}
        material={materials.coin}
        position={[151.741, 134.676, 900.87]}
        rotation={[-1.625, -0.133, 1.707]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder248_coin_0.geometry}
        material={materials.coin}
        position={[116.856, 134.631, 901.355]}
        rotation={[-1.557, -0.026, 0.528]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder255_coin_0.geometry}
        material={materials.coin}
        position={[200.518, 135.68, 920.065]}
        rotation={[-1.712, 0.176, -0.414]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder256_coin_0.geometry}
        material={materials.coin}
        position={[126.045, 151.213, 946.966]}
        rotation={[-Math.PI / 2, 0, 0.606]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder257_coin_0.geometry}
        material={materials.coin}
        position={[119.228, 133.742, 871.505]}
        rotation={[-1.588, -0.037, -1.975]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder258_coin_0.geometry}
        material={materials.coin}
        position={[143.035, 135.464, 935.891]}
        rotation={[-1.544, -0.057, 0.4]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder259_coin_0.geometry}
        material={materials.coin}
        position={[116.022, 135.683, 935.83]}
        rotation={[-1.441, -0.081, 2.797]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder261_coin_0.geometry}
        material={materials.coin}
        position={[131.614, 134.667, 982.509]}
        rotation={[-1.559, 0, 1.918]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder262_coin_0.geometry}
        material={materials.coin}
        position={[106.822, 135.764, 967.996]}
        rotation={[-1.401, 0.008, 2.315]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder219_coin_0.geometry}
        material={materials.coin}
        position={[-49.944, -4.819, 473.552]}
        rotation={[-1.375, -0.134, 0.689]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder033_coin_0.geometry}
        material={materials.coin}
        position={[-557.293, 148.816, 795.928]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder035_coin_0.geometry}
        material={materials.coin}
        position={[-876.475, -0.612, 320.93]}
        rotation={[-Math.PI / 2, 0, 1.126]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder031_coin_0.geometry}
        material={materials.coin}
        position={[-979.936, 144.352, 1214.099]}
        rotation={[-Math.PI / 2, 0, 0.575]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder032_coin_0.geometry}
        material={materials.coin}
        position={[-1005.163, 143.985, 1260.074]}
        rotation={[-Math.PI / 2, 0, -2.249]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder036_coin_0.geometry}
        material={materials.coin}
        position={[-975.124, 146.798, 1228.672]}
        rotation={[-1.355, 0.053, -1.32]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder037_coin_0.geometry}
        material={materials.coin}
        position={[-1007.057, 144.352, 1229.847]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder038_coin_0.geometry}
        material={materials.coin}
        position={[-1008.497, 148.407, 1228.753]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder039_coin_0.geometry}
        material={materials.coin}
        position={[-1006.04, 152.399, 1227.788]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder040_coin_0.geometry}
        material={materials.coin}
        position={[-1008.593, 156.353, 1227.129]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder041_coin_0.geometry}
        material={materials.coin}
        position={[-462.143, 148.659, 883.77]}
        rotation={[-Math.PI / 2, 0, 0.575]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder042_coin_0.geometry}
        material={materials.coin}
        position={[-487.37, 148.292, 929.745]}
        rotation={[-Math.PI / 2, 0, -2.249]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder043_coin_0.geometry}
        material={materials.coin}
        position={[-457.331, 151.105, 898.343]}
        rotation={[-1.355, 0.053, -1.32]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder044_coin_0.geometry}
        material={materials.coin}
        position={[-489.265, 148.659, 899.518]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder045_coin_0.geometry}
        material={materials.coin}
        position={[-490.705, 152.715, 898.424]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder046_coin_0.geometry}
        material={materials.coin}
        position={[-488.247, 156.706, 897.459]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder047_coin_0.geometry}
        material={materials.coin}
        position={[-490.8, 160.66, 896.8]}
        rotation={[-Math.PI / 2, 0, -2.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder048_coin_0.geometry}
        material={materials.coin}
        position={[-488.092, 164.636, 897.526]}
        rotation={[-Math.PI / 2, 0, -2.851]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder049_coin_0.geometry}
        material={materials.coin}
        position={[-489.186, 168.691, 898.966]}
        rotation={[-Math.PI / 2, 0, -2.851]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder050_coin_0.geometry}
        material={materials.coin}
        position={[-490.151, 172.683, 896.509]}
        rotation={[-Math.PI / 2, 0, -2.851]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder051_coin_0.geometry}
        material={materials.coin}
        position={[-490.81, 176.636, 899.061]}
        rotation={[-Math.PI / 2, 0, -2.851]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder052_coin_0.geometry}
        material={materials.coin}
        position={[-472.266, 148.292, 812.39]}
        rotation={[-Math.PI / 2, 0, -1.241]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder053_coin_0.geometry}
        material={materials.coin}
        position={[-508.332, 148.292, 818.413]}
        rotation={[-Math.PI / 2, 0, 1.399]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder054_coin_0.geometry}
        material={materials.coin}
        position={[-960.316, 144.352, 1272.354]}
        rotation={[-Math.PI / 2, 0, -0.683]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder055_coin_0.geometry}
        material={materials.coin}
        position={[-1026.714, 144.352, 1297.564]}
        rotation={[-Math.PI / 2, 0, 0.206]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder056_coin_0.geometry}
        material={materials.coin}
        position={[-943.148, 144.352, 1292.164]}
        rotation={[-Math.PI / 2, 0, 1.761]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder057_coin_0.geometry}
        material={materials.coin}
        position={[-1045.821, -7.034, 917.347]}
        rotation={[-Math.PI / 2, 0, -0.276]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder058_coin_0.geometry}
        material={materials.coin}
        position={[-991.535, -7.034, 941.799]}
        rotation={[-Math.PI / 2, 0, 2.167]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder059_coin_0.geometry}
        material={materials.coin}
        position={[-1032.302, -7.372, 967.986]}
        rotation={[-Math.PI / 2, 0, 0.944]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder060_coin_0.geometry}
        material={materials.coin}
        position={[-1005.932, -7.372, 1006.591]}
        rotation={[-Math.PI / 2, 0, -0.565]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder061_coin_0.geometry}
        material={materials.coin}
        position={[-70.749, 195.263, 169.791]}
        rotation={[-Math.PI / 2, 0, -0.276]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder062_coin_0.geometry}
        material={materials.coin}
        position={[-16.462, 195.263, 194.243]}
        rotation={[-Math.PI / 2, 0, 2.167]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder063_coin_0.geometry}
        material={materials.coin}
        position={[-57.23, 194.924, 220.43]}
        rotation={[-Math.PI / 2, 0, 0.944]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder064_coin_0.geometry}
        material={materials.coin}
        position={[-55.99, 194.924, 194.069]}
        rotation={[-Math.PI / 2, 0, 0.138]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder034_coin_0.geometry}
        material={materials.coin}
        position={[-92.786, 195.263, 218.431]}
        rotation={[-Math.PI / 2, 0, -0.276]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder070_coin_0.geometry}
        material={materials.coin}
        position={[-533.071, 148.659, 778.901]}
        rotation={[-Math.PI / 2, 0, 2.434]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder071_coin_0.geometry}
        material={materials.coin}
        position={[-531.66, 152.715, 777.77]}
        rotation={[-Math.PI / 2, 0, 2.434]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder072_coin_0.geometry}
        material={materials.coin}
        position={[-531.32, 156.706, 780.388]}
        rotation={[-Math.PI / 2, 0, 2.434]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder073_coin_0.geometry}
        material={materials.coin}
        position={[-530.062, 160.66, 778.072]}
        rotation={[-Math.PI / 2, 0, 2.434]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder074_coin_0.geometry}
        material={materials.coin}
        position={[-312.391, -7.419, 225.78]}
        rotation={[-Math.PI / 2, 0, -0.881]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder075_coin_0.geometry}
        material={materials.coin}
        position={[-338.228, -7.419, 236.344]}
        rotation={[-Math.PI / 2, 0, -0.127]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder076_coin_0.geometry}
        material={materials.coin}
        position={[-343.532, -7.419, 210.189]}
        rotation={[-Math.PI / 2, 0, -2.571]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder077_coin_0.geometry}
        material={materials.coin}
        position={[-404.198, -7.419, 236.535]}
        rotation={[-Math.PI / 2, 0, -2.927]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder078_coin_0.geometry}
        material={materials.coin}
        position={[-366.709, -7.419, 131.779]}
        rotation={[-Math.PI / 2, 0, 1.486]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder079_coin_0.geometry}
        material={materials.coin}
        position={[-281.133, -7.419, 115.578]}
        rotation={[-Math.PI / 2, 0, 2.24]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder080_coin_0.geometry}
        material={materials.coin}
        position={[-400.567, -7.419, 153.18]}
        rotation={[-Math.PI / 2, 0, -0.204]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder081_coin_0.geometry}
        material={materials.coin}
        position={[-329.674, -7.419, 160.185]}
        rotation={[-Math.PI / 2, 0, -0.56]}
        scale={100}
      />
      <mesh
        geometry={nodes.Plane_base_0.geometry}
        material={materials.base}
        position={[-381.507, -77.83, 631.915]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube001_columns_0.geometry}
        material={materials.columns}
        position={[-364.714, 317.112, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube006_columns_0.geometry}
        material={materials.columns}
        position={[-991.169, 317.112, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube012_columns_0.geometry}
        material={materials.columns}
        position={[262.274, 100, 623.852]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube013_columns_0.geometry}
        material={materials.columns}
        position={[262.274, 100, 1249.411]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube015_columns_0.geometry}
        material={materials.columns}
        position={[260.155, 317.112, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube028_columns_0.geometry}
        material={materials.columns}
        position={[-991.169, 66.664, 1249.411]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube029_columns_0.geometry}
        material={materials.columns}
        position={[-225.548, 317.112, 1249.411]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube005_walls_0.geometry}
        material={materials.walls}
        position={[-678.372, 375.851, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube007_walls_0.geometry}
        material={materials.walls}
        position={[262.406, 304.617, 312.061]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube004_walls_0.geometry}
        material={materials.walls}
        position={[-52.279, 304.617, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube014_walls_0.geometry}
        material={materials.walls}
        position={[262.406, 304.617, 935.643]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube003_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[-681.463, 621.247, 0.278]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube011_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[-801.199, 17.584, -0.738]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube008_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[-48.685, 621.247, 0.278]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube009_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[262.246, 621.247, 308.382]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube010_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[262.246, 621.247, 939.188]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[262.06, 137.737, 936.678]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube016_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[261.21, 461.174, 936.168]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube022_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[-868.64, 44.175, 165.803]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube024_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[210.994, 310.307, 625.576]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube030_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[-808.377, -8.224, 366.741]}
        rotation={[-Math.PI / 2, 0, 0.106]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube031_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[-312.193, -8.224, 331.693]}
        rotation={[-Math.PI / 2, 0, -1.31]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube032_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[42.406, -8.224, 681.48]}
        rotation={[-Math.PI / 2, 0, -0.061]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube033_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[-208.004, -8.224, 847.861]}
        rotation={[-Math.PI / 2, 0, 0.101]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube034_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[-12.413, -8.224, 1135.273]}
        rotation={[-Math.PI / 2, 0, 0.084]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube035_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[-618.073, -8.224, 1056.256]}
        rotation={[-Math.PI / 2, 0, -0.054]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube036_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[-533.37, -8.224, 618.222]}
        rotation={[-Math.PI / 2, 0, -0.067]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube037_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[-138.002, 235.851, 25.458]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube038_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[-5.894, 492.364, 25.458]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube039_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[120.413, 102.429, 25.458]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube026_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[237.323, 417.413, 440.776]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube041_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[237.323, 328.279, 199.428]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube042_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[237.323, 132.736, 289.176]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube043_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[237.323, 198.031, 396.9]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube044_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[237.323, 512.867, 872.572]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube045_stone_decorations_0.geometry}
        material={materials.stone_decorations}
        position={[237.323, 564.39, 804.526]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube047_stool_0.geometry}
        material={materials.stool}
        position={[-965.984, 43.109, 879.475]}
        rotation={[-0.071, -0.484, -0.033]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube048_stool_0.geometry}
        material={materials.stool}
        position={[-709.319, 89.703, 1055.664]}
        rotation={[-1.588, -0.085, -0.203]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube049_stool_0.geometry}
        material={materials.stool}
        position={[-450.746, 84.801, 1052.595]}
        rotation={[-Math.PI / 2, 0, 1.633]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube050_stool_0.geometry}
        material={materials.stool}
        position={[-693.939, 84.801, 640.405]}
        rotation={[-Math.PI / 2, 0, -3.008]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube051_stool_0.geometry}
        material={materials.stool}
        position={[-397.162, 84.801, 661.014]}
        rotation={[-Math.PI / 2, 0, -0.349]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube054_stool_0.geometry}
        material={materials.stool}
        position={[111.729, 84.801, 933.713]}
        rotation={[-Math.PI / 2, 0, -1.767]}
        scale={100}
      />
      <mesh
        geometry={nodes.tebleLarge_table_0.geometry}
        material={materials.table}
        position={[-551.307, 100.578, 852.307]}
        rotation={[-Math.PI / 2, 0, -0.092]}
        scale={100}
      />

      <mesh
        geometry={nodes.tableSmall_table_0.geometry}
        material={materials.table}
        position={[146.646, 90.065, 932.336]}
        rotation={[-Math.PI / 2, 0, 1.597]}
        scale={100}
      />

      <mesh
        geometry={nodes.chestBottom_chest_0.geometry}
        material={materials.chest}
        position={[-29.964, 59.551, 236.11]}
        rotation={[-Math.PI / 2, 0, -0.53]}
        scale={100}
      />
      <mesh
        geometry={nodes.chestTop_chest_0.geometry}
        material={materials.chest}
        position={[-30.11, 170.088, 236.35]}
        rotation={[-Math.PI / 2, 0, -0.53]}
        scale={100}
      />
      <mesh
        geometry={nodes.chestHinges_chest_0.geometry}
        material={materials.chest}
        position={[28.306, 130.404, 136.573]}
        rotation={[-Math.PI / 2, 0, -0.53]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder021_sword_0.geometry}
        material={materials.sword}
        position={[188.046, -9.063, 465.563]}
        rotation={[-Math.PI / 2, 0.143, -Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder022_sword_0.geometry}
        material={materials.sword}
        position={[188.046, -9.063, 361.034]}
        rotation={[-Math.PI / 2, 0.12, -Math.PI]}
        scale={100}
      />
      {/* <mesh
        geometry={nodes.Cylinder023_sword_0.geometry}
        material={materials.sword}
        position={[102.017, 202.376, 153.922]}
        rotation={[0.052, -0.998, 1.617]}
        scale={100}
      /> */}
      <mesh
        geometry={nodes.Cylinder024_sword_0.geometry}
        material={materials.sword}
        position={[-687.1, 2.273, 1301.859]}
        rotation={[3.064, 1.264, -1.495]}
        scale={100}
      />
      <mesh
        geometry={nodes.barrel_barrel_0.geometry}
        material={materials.barrel}
        position={[-971.519, 76.716, 541.655]}
        rotation={[-Math.PI / 2, 0, 0.452]}
        scale={100}
      />
      <mesh
        geometry={nodes.box_box_0.geometry}
        material={materials.material}
        position={[23.934, 54.684, 1288.321]}
        rotation={[-Math.PI / 2, 0, -0.091]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("models/castle.glb");
