/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Walking.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Walking(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("models/Walking.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Hips} />
        </group>
        <group name="Armature001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Paladin_J_Nordstrom"
            geometry={nodes.Paladin_J_Nordstrom.geometry}
            material={materials.Paladin_MAT}
            skeleton={nodes.Paladin_J_Nordstrom.skeleton}
          />
          <skinnedMesh
            name="Paladin_J_Nordstrom_Helmet"
            geometry={nodes.Paladin_J_Nordstrom_Helmet.geometry}
            material={materials.Paladin_MAT}
            skeleton={nodes.Paladin_J_Nordstrom_Helmet.skeleton}
          />
          <skinnedMesh
            name="Paladin_J_Nordstrom_Shield"
            geometry={nodes.Paladin_J_Nordstrom_Shield.geometry}
            material={materials.Paladin_MAT}
            skeleton={nodes.Paladin_J_Nordstrom_Shield.skeleton}
          />
          <skinnedMesh
            name="Paladin_J_Nordstrom_Sword"
            geometry={nodes.Paladin_J_Nordstrom_Sword.geometry}
            material={materials.Paladin_MAT}
            skeleton={nodes.Paladin_J_Nordstrom_Sword.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/Walking.glb");
